// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: pb/itemssvc/v1/itemssvc.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ItemType int32

const (
	ItemType_FRAGILE      ItemType = 0
	ItemType_ELECTRONICS  ItemType = 1
	ItemType_RADIO_ACTIVE ItemType = 2
	ItemType_BIO_HAZARD   ItemType = 3
)

// Enum value maps for ItemType.
var (
	ItemType_name = map[int32]string{
		0: "FRAGILE",
		1: "ELECTRONICS",
		2: "RADIO_ACTIVE",
		3: "BIO_HAZARD",
	}
	ItemType_value = map[string]int32{
		"FRAGILE":      0,
		"ELECTRONICS":  1,
		"RADIO_ACTIVE": 2,
		"BIO_HAZARD":   3,
	}
)

func (x ItemType) Enum() *ItemType {
	p := new(ItemType)
	*p = x
	return p
}

func (x ItemType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ItemType) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_itemssvc_v1_itemssvc_proto_enumTypes[0].Descriptor()
}

func (ItemType) Type() protoreflect.EnumType {
	return &file_pb_itemssvc_v1_itemssvc_proto_enumTypes[0]
}

func (x ItemType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ItemType.Descriptor instead.
func (ItemType) EnumDescriptor() ([]byte, []int) {
	return file_pb_itemssvc_v1_itemssvc_proto_rawDescGZIP(), []int{0}
}

type CreateItemsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*ItemResponse `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *CreateItemsResponse) Reset() {
	*x = CreateItemsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_itemssvc_v1_itemssvc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateItemsResponse) ProtoMessage() {}

func (x *CreateItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_itemssvc_v1_itemssvc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateItemsResponse.ProtoReflect.Descriptor instead.
func (*CreateItemsResponse) Descriptor() ([]byte, []int) {
	return file_pb_itemssvc_v1_itemssvc_proto_rawDescGZIP(), []int{0}
}

func (x *CreateItemsResponse) GetItems() []*ItemResponse {
	if x != nil {
		return x.Items
	}
	return nil
}

type CreateItemsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*ItemRequest `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *CreateItemsRequest) Reset() {
	*x = CreateItemsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_itemssvc_v1_itemssvc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateItemsRequest) ProtoMessage() {}

func (x *CreateItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_itemssvc_v1_itemssvc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateItemsRequest.ProtoReflect.Descriptor instead.
func (*CreateItemsRequest) Descriptor() ([]byte, []int) {
	return file_pb_itemssvc_v1_itemssvc_proto_rawDescGZIP(), []int{1}
}

func (x *CreateItemsRequest) GetItems() []*ItemRequest {
	if x != nil {
		return x.Items
	}
	return nil
}

type ItemResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ReturnID    string  `protobuf:"bytes,2,opt,name=returnID,proto3" json:"returnID,omitempty"`
	Title       string  `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description string  `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Quantity    int32   `protobuf:"varint,5,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Weight      float32 `protobuf:"fixed32,6,opt,name=weight,proto3" json:"weight,omitempty"`
	Height      float32 `protobuf:"fixed32,7,opt,name=height,proto3" json:"height,omitempty"`
	Width       float32 `protobuf:"fixed32,8,opt,name=width,proto3" json:"width,omitempty"`
	Type        string  `protobuf:"bytes,9,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *ItemResponse) Reset() {
	*x = ItemResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_itemssvc_v1_itemssvc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemResponse) ProtoMessage() {}

func (x *ItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_itemssvc_v1_itemssvc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemResponse.ProtoReflect.Descriptor instead.
func (*ItemResponse) Descriptor() ([]byte, []int) {
	return file_pb_itemssvc_v1_itemssvc_proto_rawDescGZIP(), []int{2}
}

func (x *ItemResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ItemResponse) GetReturnID() string {
	if x != nil {
		return x.ReturnID
	}
	return ""
}

func (x *ItemResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ItemResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ItemResponse) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *ItemResponse) GetWeight() float32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *ItemResponse) GetHeight() float32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *ItemResponse) GetWidth() float32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *ItemResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type ItemRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReturnID    string   `protobuf:"bytes,1,opt,name=returnID,proto3" json:"returnID,omitempty"`
	Title       string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Quantity    int32    `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Weight      float32  `protobuf:"fixed32,5,opt,name=weight,proto3" json:"weight,omitempty"`
	Height      float32  `protobuf:"fixed32,6,opt,name=height,proto3" json:"height,omitempty"`
	Width       float32  `protobuf:"fixed32,7,opt,name=width,proto3" json:"width,omitempty"`
	Type        ItemType `protobuf:"varint,8,opt,name=type,proto3,enum=pb.itemsvc.v1.ItemType" json:"type,omitempty"`
}

func (x *ItemRequest) Reset() {
	*x = ItemRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_itemssvc_v1_itemssvc_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemRequest) ProtoMessage() {}

func (x *ItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_itemssvc_v1_itemssvc_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemRequest.ProtoReflect.Descriptor instead.
func (*ItemRequest) Descriptor() ([]byte, []int) {
	return file_pb_itemssvc_v1_itemssvc_proto_rawDescGZIP(), []int{3}
}

func (x *ItemRequest) GetReturnID() string {
	if x != nil {
		return x.ReturnID
	}
	return ""
}

func (x *ItemRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ItemRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ItemRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *ItemRequest) GetWeight() float32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *ItemRequest) GetHeight() float32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *ItemRequest) GetWidth() float32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *ItemRequest) GetType() ItemType {
	if x != nil {
		return x.Type
	}
	return ItemType_FRAGILE
}

var File_pb_itemssvc_v1_itemssvc_proto protoreflect.FileDescriptor

var file_pb_itemssvc_v1_itemssvc_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x70, 0x62, 0x2f, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x73, 0x76, 0x63, 0x2f, 0x76, 0x31,
	0x2f, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x73, 0x76, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0d, 0x70, 0x62, 0x2e, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x76, 0x63, 0x2e, 0x76, 0x31, 0x22, 0x48,
	0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x70, 0x62, 0x2e, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x76,
	0x63, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x46, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x30,
	0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x70, 0x62, 0x2e, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x76, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x74,
	0x65, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73,
	0x22, 0xe8, 0x01, 0x0a, 0x0c, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x49, 0x44, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x49, 0x44, 0x12, 0x14, 0x0a,
	0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69,
	0x74, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74,
	0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74,
	0x79, 0x12, 0x16, 0x0a, 0x06, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x06, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69,
	0x67, 0x68, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68,
	0x74, 0x12, 0x14, 0x0a, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x18, 0x08, 0x20, 0x01, 0x28, 0x02,
	0x52, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0xf0, 0x01, 0x0a, 0x0b,
	0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x72,
	0x65, 0x74, 0x75, 0x72, 0x6e, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72,
	0x65, 0x74, 0x75, 0x72, 0x6e, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x20, 0x0a,
	0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x1a, 0x0a, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x77,
	0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x77, 0x65, 0x69,
	0x67, 0x68, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x02, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x77,
	0x69, 0x64, 0x74, 0x68, 0x18, 0x07, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x77, 0x69, 0x64, 0x74,
	0x68, 0x12, 0x2b, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x17, 0x2e, 0x70, 0x62, 0x2e, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x76, 0x63, 0x2e, 0x76, 0x31, 0x2e,
	0x49, 0x74, 0x65, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x2a, 0x4a,
	0x0a, 0x08, 0x49, 0x74, 0x65, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x46, 0x52,
	0x41, 0x47, 0x49, 0x4c, 0x45, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x45, 0x4c, 0x45, 0x43, 0x54,
	0x52, 0x4f, 0x4e, 0x49, 0x43, 0x53, 0x10, 0x01, 0x12, 0x10, 0x0a, 0x0c, 0x52, 0x41, 0x44, 0x49,
	0x4f, 0x5f, 0x41, 0x43, 0x54, 0x49, 0x56, 0x45, 0x10, 0x02, 0x12, 0x0e, 0x0a, 0x0a, 0x42, 0x49,
	0x4f, 0x5f, 0x48, 0x41, 0x5a, 0x41, 0x52, 0x44, 0x10, 0x03, 0x32, 0x61, 0x0a, 0x07, 0x49, 0x74,
	0x65, 0x6d, 0x53, 0x76, 0x63, 0x12, 0x56, 0x0a, 0x0b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x49,
	0x74, 0x65, 0x6d, 0x73, 0x12, 0x21, 0x2e, 0x70, 0x62, 0x2e, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x76,
	0x63, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x70, 0x62, 0x2e, 0x69, 0x74, 0x65,
	0x6d, 0x73, 0x76, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x49, 0x74,
	0x65, 0x6d, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x10, 0x5a,
	0x0e, 0x70, 0x62, 0x2f, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x73, 0x76, 0x63, 0x2f, 0x76, 0x31, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_itemssvc_v1_itemssvc_proto_rawDescOnce sync.Once
	file_pb_itemssvc_v1_itemssvc_proto_rawDescData = file_pb_itemssvc_v1_itemssvc_proto_rawDesc
)

func file_pb_itemssvc_v1_itemssvc_proto_rawDescGZIP() []byte {
	file_pb_itemssvc_v1_itemssvc_proto_rawDescOnce.Do(func() {
		file_pb_itemssvc_v1_itemssvc_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_itemssvc_v1_itemssvc_proto_rawDescData)
	})
	return file_pb_itemssvc_v1_itemssvc_proto_rawDescData
}

var file_pb_itemssvc_v1_itemssvc_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pb_itemssvc_v1_itemssvc_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pb_itemssvc_v1_itemssvc_proto_goTypes = []interface{}{
	(ItemType)(0),               // 0: pb.itemsvc.v1.ItemType
	(*CreateItemsResponse)(nil), // 1: pb.itemsvc.v1.CreateItemsResponse
	(*CreateItemsRequest)(nil),  // 2: pb.itemsvc.v1.CreateItemsRequest
	(*ItemResponse)(nil),        // 3: pb.itemsvc.v1.ItemResponse
	(*ItemRequest)(nil),         // 4: pb.itemsvc.v1.ItemRequest
}
var file_pb_itemssvc_v1_itemssvc_proto_depIdxs = []int32{
	3, // 0: pb.itemsvc.v1.CreateItemsResponse.items:type_name -> pb.itemsvc.v1.ItemResponse
	4, // 1: pb.itemsvc.v1.CreateItemsRequest.items:type_name -> pb.itemsvc.v1.ItemRequest
	0, // 2: pb.itemsvc.v1.ItemRequest.type:type_name -> pb.itemsvc.v1.ItemType
	2, // 3: pb.itemsvc.v1.ItemSvc.CreateItems:input_type -> pb.itemsvc.v1.CreateItemsRequest
	1, // 4: pb.itemsvc.v1.ItemSvc.CreateItems:output_type -> pb.itemsvc.v1.CreateItemsResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pb_itemssvc_v1_itemssvc_proto_init() }
func file_pb_itemssvc_v1_itemssvc_proto_init() {
	if File_pb_itemssvc_v1_itemssvc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_itemssvc_v1_itemssvc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateItemsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_itemssvc_v1_itemssvc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateItemsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_itemssvc_v1_itemssvc_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ItemResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_itemssvc_v1_itemssvc_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ItemRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_itemssvc_v1_itemssvc_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_itemssvc_v1_itemssvc_proto_goTypes,
		DependencyIndexes: file_pb_itemssvc_v1_itemssvc_proto_depIdxs,
		EnumInfos:         file_pb_itemssvc_v1_itemssvc_proto_enumTypes,
		MessageInfos:      file_pb_itemssvc_v1_itemssvc_proto_msgTypes,
	}.Build()
	File_pb_itemssvc_v1_itemssvc_proto = out.File
	file_pb_itemssvc_v1_itemssvc_proto_rawDesc = nil
	file_pb_itemssvc_v1_itemssvc_proto_goTypes = nil
	file_pb_itemssvc_v1_itemssvc_proto_depIdxs = nil
}
